import secrets
import bcrypt
from cryptography.fernet import Fernet
import os
from dotenv import load_dotenv
import random
import requests

load_dotenv()

# HASHING (Password Security)
def hash_password(plain_text_password: str) -> str:
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(plain_text_password.encode('utf-8'), salt)
    return hashed.decode('utf-8')

def verify_password(plain_text_password: str, hashed_password: str) -> bool:
    return bcrypt.checkpw(plain_text_password.encode('utf-8'), hashed_password.encode('utf-8'))

# SYMMETRIC ENCRYPTION (Data at Rest)
STATIC_SECRET_KEY = b'vX9P-Q8mN_uG5F2T7jL4wR1eY3cK0bM8oH6aD5sS9A0=' 
cipher_suite = Fernet(STATIC_SECRET_KEY)

def encrypt_data(sensitive_data: str) -> str:
    encrypted_text = cipher_suite.encrypt(sensitive_data.encode('utf-8'))
    return encrypted_text.decode('utf-8')

def decrypt_data(encrypted_data: str) -> str:
    decrypted_text = cipher_suite.decrypt(encrypted_data.encode('utf-8'))
    return decrypted_text.decode('utf-8')

# SECURE PROTOCOLS (Secure Mail via Brevo API - BOT-SAFE VERSION)
def generate_verification_token() -> str:
    return secrets.token_urlsafe(32)

def send_real_secure_email(receiver_email: str, token: str):
    api_key = os.getenv("BREVO_API_KEY")
    # HARDCODED VERIFIED DOMAIN
    sender_email = "support@kevincodes.tech" 
    
    if not api_key:
        print(" Error: Missing BREVO_API_KEY.")
        return

    verification_link = f"https://vault-backend-api-szxu.onrender.com/verify/{token}"
    url = "https://api.brevo.com/v3/smtp/email"
    
    headers = {"accept": "application/json", "api-key": api_key, "content-type": "application/json"}
    
    payload = {
        "sender": {"name": "Portfolio Project Demo", "email": sender_email},
        "to": [{"email": receiver_email}],
        "subject": "[TEST] Account Verification - Developer Portfolio",
        "htmlContent": f"""
            <div style='background:#f4f4f5; padding:20px; font-family: sans-serif;'>
                <p style='color:#b91c1c; font-weight:bold; border: 2px solid #b91c1c; padding: 10px;'>
                ⚠️ DISCLAIMER: This is a test email generated by a university software engineering portfolio project. No real data is involved.</p>
                <h3>Welcome to the simulated Secure Vault Application!</h3>
                <p>Please click the link below to verify this test account:</p>
                <p><a href='{verification_link}' style='color: #512da8; font-weight: bold;'>{verification_link}</a></p>
            </div>
        """
    }
    try:
        requests.post(url, json=payload, headers=headers).raise_for_status()
        print(f" Test verification email sent to {receiver_email}!")
    except Exception as e:
        print(f" Failed to send email: {e}")

def send_password_reset_email(receiver_email: str, token: str):
    api_key = os.getenv("BREVO_API_KEY")
    sender_email = "support@kevincodes.tech" 
    if not api_key: return

    reset_link = f"https://vault-backend-api-szxu.onrender.com/reset-password-page/{token}"
    url = "https://api.brevo.com/v3/smtp/email"
    headers = {"accept": "application/json", "api-key": api_key, "content-type": "application/json"}
    
    payload = {
        "sender": {"name": "Portfolio Project Demo", "email": sender_email},
        "to": [{"email": receiver_email}],
        "subject": "[TEST] Password Reset - Developer Portfolio",
        "htmlContent": f"""
            <div style='background:#f4f4f5; padding:20px; font-family: sans-serif;'>
                <p style='color:#b91c1c; font-weight:bold; border: 2px solid #b91c1c; padding: 10px;'>
                ⚠️ DISCLAIMER: This is a test email generated by a university software engineering portfolio project.</p>
                <h3>Account Password Reset</h3>
                <p>Please click the link below to test the password reset functionality:</p>
                <p><a href='{reset_link}' style='color: #512da8; font-weight: bold;'>{reset_link}</a></p>
            </div>
        """
    }
    try:
        requests.post(url, json=payload, headers=headers)
        print(f" Test reset email sent to {receiver_email}!")
    except Exception as e:
        print(f"Failed: {e}")

def generate_otp() -> str:
    return str(random.randint(100000, 999999))

def send_transfer_otp_email(receiver_email: str, otp: str, amount: str, recipient: str):
    api_key = os.getenv("BREVO_API_KEY")
    sender_email = "support@kevincodes.tech" 
    if not api_key: return

    url = "https://api.brevo.com/v3/smtp/email"
    headers = {"accept": "application/json", "api-key": api_key, "content-type": "application/json"}
    
    payload = {
        "sender": {"name": "Portfolio Project Demo", "email": sender_email},
        "to": [{"email": receiver_email}],
        "subject": f"[TEST] Authorization Code: {otp} - Developer Portfolio",
        "htmlContent": f"""
            <div style='background:#f4f4f5; padding:20px; font-family: sans-serif;'>
                <p style='color:#b91c1c; font-weight:bold; border: 2px solid #b91c1c; padding: 10px;'>
                ⚠️ DISCLAIMER: This is a test email generated by a university software engineering portfolio project.</p>
                <h3>Simulated Action Authorization</h3>
                <p>You requested a test action of <strong>{amount} units</strong> to target <strong>{recipient}</strong>.</p>
                <p>Your test authorization code is: <h2 style='color:blue;'>{otp}</h2></p>
            </div>
        """
    }
    try:
        requests.post(url, json=payload, headers=headers)
        print(f" Test OTP email sent to {receiver_email}!")
    except Exception as e:
        print(f"Failed: {e}")